version: '3.5'

services:
  gateway:
    build:
      context: ${REL_PATH_GATEWAY:-.}/
      dockerfile: ./docker/Dockerfile
    image: gateway
    container_name: ${APP_NAME}_gateway
    restart: unless-stopped
    working_dir: /var/www/app
    volumes:
      - ${REL_PATH_GATEWAY:-.}/:/var/www/app
  nginx_gateway:
    image: nginx:alpine
    container_name: ${APP_NAME}_gateway_nginx
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - ${REL_PATH_GATEWAY:-.}/:/var/www/app
      - ${REL_PATH_GATEWAY:-.}/docker/nginx:/etc/nginx/conf.d
    depends_on:
      - gateway
networks:
  default:
    name: microservices
